### PR TITLE
Home and Category pages.

### PR DESCRIPTION
**Pull request by samyukthasudhakar**
As part of the PR, I have created the following screens : 

- Home Page : https://home-and-categories.netlify.app/index.html

home-page

- Categories Page : https://home-and-categories.netlify.app/categories.html
categories-page

Commits to review :
- Home Page : [283698b](https://github.com/samyukthasudhakar/QuizApp/pull/1/commits/283698b4b8d66ca2f9991af4017d654222fbb698)
- Categories Page : [91b824e](https://github.com/samyukthasudhakar/QuizApp/pull/1/commits/91b824e1f379fe06dc29d41e0752535f0f7ecbe5)

### CODE REVIEW

**Review by devsurajrai — APPROVED** [review]
Looks awesome. you're good to go. Just a typo in the hompage's footer.

**Review by venkateshwarans — APPROVED** [review]
All look good. Neat and clean.

**Comment by samyukthasudhakar** [comment]
> Looks awesome. you're good to go. Just a typo in the hompage's footer.

Thank you for pointing it out. Fixed it 👍🏽

**Comment by samyukthasudhakar** [comment]
> All look good. Neat and clean.

Thank you !

**Pull request merged**
